# A sample Gemfile
source "https://rubygems.org"

gem 'bundler'
gem 'github_api'
gem 'require_all','2.0.0'
gem 'json','2.1.0'
gem 'faraday','0.12.2'
gem 'highline', '~> 2.0'
gem 'git', '1.5.0'

group :test do
  gem 'rspec', '3.8.0'
  gem "simplecov", "0.16.1"
  gem 'rspec-core', "3.8.0"
  gem 'pry'
  gem 'rspec-mocks', "3.8.0"
  gem 'rspec-expectations', "3.8.1"
  gem 'vcr', "4.0.0"
  gem 'webmock', "3.4.2"
end
