require 'json'
require 'git'
require 'github_api'

task :default do
  gemspec = Gem::Specification.load(File.absolute_path('../odyssey.gemspec'))
  source_code_uri = gemspec.metadata.fetch("source_code_uri")
  repo, owner = source_code_uri.split("/").reverse
  credentials_file = File.expand_path('~/.odyssey/credentials.json')
  
  if File.exists?(credentials_file) # Ok credentials file exists
    content = JSON.parse(File.read(credentials_file)) # Read the file
    oauth_token = content.fetch('github_oauth'){ nil }
    if oauth_token 
      # Ok oauth_token exists
      # Fetch audit-temples repo
      github = Github.new oauth_token: oauth_token
      repo_contents = github.repos.contents user: owner, repo: repo
      audit_templates = repo_contents.get path: 'Audit-Templates'
      submodule_git_url = audit_templates.submodule_git_url
      submodule_git_url_split = submodule_git_url.split("/")
      submodule_git_url_owner = submodule_git_url_split[0].reverse.chomp("git@github.com:".reverse).reverse
      submodule_git_url_repo = submodule_git_url_split[1]

      submodule_git_url = "https://#{oauth_token}:x-oauth-basic@github.com/#{submodule_git_url_owner}/#{submodule_git_url_repo}"

      Git.clone(submodule_git_url, "Audit-Templates", path: File.expand_path("..", Dir.pwd))
    end
  end
end
